//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkalmazas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Vetítés = new HashSet<Vetítés>();
        }
    
        public int FILM_PK { get; set; }
        public string CIM { get; set; }
        public int JATEKIDO { get; set; }
        public int MUFAJ_FK { get; set; }
        public int KORHATAR { get; set; }
        public string SZINKRON { get; set; }
    
        public virtual Műfaj Műfaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vetítés> Vetítés { get; set; }
    }
}
