//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkalmazas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Időpont> Időpont { get; set; }
        public virtual DbSet<Jegy> Jegy { get; set; }
        public virtual DbSet<Kategória> Kategória { get; set; }
        public virtual DbSet<Mozi> Mozi { get; set; }
        public virtual DbSet<Műfaj> Műfaj { get; set; }
        public virtual DbSet<Nap> Nap { get; set; }
        public virtual DbSet<Terem> Terem { get; set; }
        public virtual DbSet<Város> Város { get; set; }
        public virtual DbSet<Vetítés> Vetítés { get; set; }
    }
}
