//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkalmazas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mozi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mozi()
        {
            this.Terem = new HashSet<Terem>();
            this.Vetítés = new HashSet<Vetítés>();
        }
    
        public int MOZI_PK { get; set; }
        public string NEV { get; set; }
        public int VAROS_FK { get; set; }
    
        public virtual Város Város { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terem> Terem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vetítés> Vetítés { get; set; }
    }
}
